site_name: Sri Lanka & Maldives vACC Documentation
site_description: Controller procedures, SOPs, references and training documentation for the Sri Lanka & Maldives vACC.
site_url: https://dogonfire7.github.io/srmvacc-docs/

nav:
  - Home: index.md

  - Maldives:
      - Velana International Airport (VRMM):
          - 0. Document information: maldives/vrmm/document-information.md
          - 1. Aerodrome information: maldives/vrmm/aerodrome-information.md
          - 2. Area of responsibility: maldives/vrmm/area-of-responsibility.md
          - 3. Clearance procedures: maldives/vrmm/clearance-procedures.md
          - 4. Pushback & startup procedures: maldives/vrmm/pushback-startup.md
          - 5. Taxi procedures: maldives/vrmm/taxi-procedures.md
          - 6. Takeoff & landing procedures: maldives/vrmm/takeoff-landing.md
          - 7. VFR & Seaplane procedures: maldives/vrmm/vfr-seaplane.md
          
theme:
  name: material
  language: en

  icon:
    logo: material/palm-tree

  font:
    text: Inter
    code: JetBrains Mono

  features:
    # Navigation
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking

    # Documentation Navigation
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.top
    - toc.follow

    # Search Bar
    - search.suggest
    - search.highlight

    # Content
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - content.tooltips

  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - search

markdown_extensions:
  - admonition
  - attr_list
  - tables
  - abbr
  - md_in_html

  - pymdownx.details

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  - pymdownx.tabbed:
      alternate_style: true

  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  - pymdownx.blocks.caption

extra_css:
  - stylesheets/extra.css
